### ISSUE TITLE
python 3.6

### ISSUE THREAD

**Issue by samdash** [prodicus/spamfilter#9]
Any Plans to make this python3 compatible. I tried to make changes accordingly but i always get 
Classified {mail} incorrectly everytime.

**Comment by tasdikrahman** [comment]
Hey @samdash , I would suggest moving to https://github.com/tasdikrahman/spammy if possible. This repository was deprecated in favor it. Closing the issue for now :)

**Comment by samdash** [comment]
thanks, is spammy python3 compatible?

**Comment by tasdikrahman** [comment]
@samdash sadly, it currently only supports 2.7.

**Comment by samdash** [comment]
no worries thanks for the quick reply, appreciate it.
